
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-4
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjgxNjQ5MjU3","is_bot":false,"login":"BrennaScholte","name":"Brenna Scholte"},"headRefName":"BrennaKaiwen-combineRestaurant","number":22,"title":"Brenna/Kaiwen/Ritvi - Change Restaurant frontend to use Java backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-4/pull/22"},{"author":{"id":"MDQ6VXNlcjcyODIzMTA3","is_bot":false,"login":"sshivani02","name":""},"headRefName":"Shivani-MovieFrontend","number":21,"title":"ss - added frontend files for Movies","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-4/pull/21"},{"author":{"id":"MDQ6VXNlcjg2NzAyODU5","is_bot":false,"login":"Joshuason55","name":"Joshua Son"},"headRefName":"Josh-frontendHotel","number":17,"title":"Josh frontend hotel","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-4/pull/17"}]
