
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-4
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMTk2MzI0","is_bot":false,"login":"ritvibhatt","name":""},"headRefName":"Ritvi-combineMovie2","number":24,"title":"rb - connect Movie frontend with backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-4/pull/24"},{"author":{"id":"MDQ6VXNlcjc4NTg0NzYz","is_bot":false,"login":"kkwen123","name":"Kaiwen Tang"},"headRefName":"Kaiwen-combineHotel","number":23,"title":"Kaiwen combine hotel","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-4/pull/23"},{"author":{"id":"MDQ6VXNlcjgxNjQ5MjU3","is_bot":false,"login":"BrennaScholte","name":"Brenna Scholte"},"headRefName":"BrennaKaiwen-combineRestaurant","number":22,"title":"Brenna/Kaiwen/Ritvi - Change Restaurant frontend to use Java backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-4/pull/22"}]
